const data = {
    products:[
        {
            _id:'1',
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:120,
            brand:'Nike',
            ratting:4.5,
            numberReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Adidas fit Shirt',
            category:'Shirts',
            image:'/images/p2.jpg',
            price:100,
            brand:'Adidas',
            ratting:4.0,
            numberReviews:10,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'Lacoste Free Shirt',
            category:'Shirts',
            image:'/images/p3.jpg',
            price:220,
            brand:'Lacoste',
            ratting:4.8,
            numberReviews:17,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Nike Slim Pant',
            category:'Pants',
            image:'/images/p4.jpg',
            price:78,
            brand:'Nike',
            ratting:4.5,
            numberReviews:14,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Puma Slim Pant',
            category:'Pants',
            image:'/images/p5.jpg',
            price:65,
            brand:'Puma',
            ratting:4.5,
            numberReviews:10,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'Adidas Fit Pant',
            category:'Pants',
            image:'/images/p6.jpg',
            price:139,
            brand:'Adidas',
            ratting:4.5,
            numberReviews:15,
            description:'high quality product',
        },
    ],
};

export default data;